apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: gcr.io/fabled-gist-342518/ors-model
          ports:
            - name: http1
              containerPort: 8000
